default_stages: [push]
exclude: ^deprecated-dune-v1-abstractions/
repos:
- repo: https://github.com/offbi/pre-commit-dbt
  rev: v1.0.0
  hooks:
  - id: dbt-compile
  - id: check-script-ref-and-source
  - id: check-model-has-description
    exclude: ^tests/
  - id: check-model-has-properties-file
    exclude: ^tests/

- repo: https://github.com/sqlfluff/sqlfluff
  rev: 2.1.0
  hooks:
  - id: sqlfluff-fix
    stages: [manual]
    args: ['--force', '--dialect', 'databricks']
    additional_dependencies:
      - dbt-databricks==1.2.1
      - sqlfluff-templater-dbt
  - id: sqlfluff-lint
    stages: [manual]
    args: ['--dialect', 'databricks']
    additional_dependencies:
      - dbt-databricks==1.2.1
      - sqlfluff-templater-dbt
